use crate::models::TargetDefinition;

pub const LINUX_CLEANUP_TARGETS: &[TargetDefinition] = &[
    TargetDefinition {
        id: "thumbnail-cache",
        name: "缩略图缓存",
        category: "cache",
        risk: "safe",
        description: "图片和视频预览缓存。删除后系统会在需要时重新生成。",
        relative_paths: &[".cache/thumbnails"],
    },
    TargetDefinition {
        id: "fontconfig-cache",
        name: "字体索引缓存",
        category: "cache",
        risk: "safe",
        description: "字体查找缓存。删除后系统会在下次加载字体时重建。",
        relative_paths: &[".cache/fontconfig"],
    },
    TargetDefinition {
        id: "shader-cache",
        name: "图形着色器缓存",
        category: "cache",
        risk: "safe",
        description: "Mesa、Radeon 和 Qt/GTK 渲染缓存。删除后会按需重建。",
        relative_paths: &[
            ".cache/mesa_shader_cache",
            ".cache/radv_builtin_shaders",
            ".cache/qtshadercache-x86_64-little_endian-lp64",
        ],
    },
    TargetDefinition {
        id: "media-framework-cache",
        name: "媒体框架缓存",
        category: "cache",
        risk: "safe",
        description: "GStreamer 和 Glycin 媒体处理缓存。删除后会按需重建。",
        relative_paths: &[".cache/gstreamer-1.0", ".cache/glycin"],
    },
    TargetDefinition {
        id: "gtk-cache",
        name: "GTK 缓存",
        category: "cache",
        risk: "safe",
        description: "GTK 组件缓存。删除后桌面应用会按需重建。",
        relative_paths: &[".cache/gtk-4.0"],
    },
    TargetDefinition {
        id: "mozilla-cache",
        name: "Firefox 缓存",
        category: "browser",
        risk: "review",
        description: "Firefox 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &[".cache/mozilla"],
    },
    TargetDefinition {
        id: "chrome-cache",
        name: "Chrome 缓存",
        category: "browser",
        risk: "review",
        description: "Chrome 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &[".cache/google-chrome"],
    },
    TargetDefinition {
        id: "chromium-cache",
        name: "Chromium 缓存",
        category: "browser",
        risk: "review",
        description: "Chromium 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &[".cache/chromium"],
    },
    TargetDefinition {
        id: "brave-cache",
        name: "Brave 缓存",
        category: "browser",
        risk: "review",
        description: "Brave 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &[".cache/BraveSoftware"],
    },
    TargetDefinition {
        id: "edge-cache",
        name: "Edge 缓存",
        category: "browser",
        risk: "review",
        description: "Microsoft Edge 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &[".cache/microsoft-edge", ".cache/Microsoft"],
    },
    TargetDefinition {
        id: "vscode-cache",
        name: "VS Code 缓存",
        category: "developer",
        risk: "review",
        description: "编辑器缓存、Webview 缓存和扩展缓存。删除后可能需要重新加载部分资源。",
        relative_paths: &[
            ".cache/vscode",
            ".cache/Code",
            ".cache/vscode-cpptools",
            ".config/Code/Cache",
            ".config/Code/CachedData",
            ".config/Code/GPUCache",
            ".config/Code/logs",
        ],
    },
    TargetDefinition {
        id: "pnpm-cache",
        name: "pnpm 缓存",
        category: "developer",
        risk: "review",
        description: "pnpm 下载缓存。删除后安装依赖时会重新下载包。",
        relative_paths: &[".cache/pnpm", ".local/share/pnpm/store"],
    },
    TargetDefinition {
        id: "cargo-cache",
        name: "Cargo 缓存",
        category: "developer",
        risk: "review",
        description: "Cargo 包和 Git 依赖缓存。删除后构建 Rust 项目时会重新下载依赖。",
        relative_paths: &[".cargo/registry/cache", ".cargo/git/db"],
    },
    TargetDefinition {
        id: "go-cache",
        name: "Go 构建缓存",
        category: "developer",
        risk: "review",
        description: "Go 构建和模块下载缓存。删除后构建时会重新生成或下载依赖。",
        relative_paths: &[".cache/go-build", "go/pkg/mod/cache"],
    },
    TargetDefinition {
        id: "playwright-cache",
        name: "Playwright 缓存",
        category: "developer",
        risk: "review",
        description: "Playwright 下载的浏览器缓存。删除后运行测试时会重新下载浏览器。",
        relative_paths: &[".cache/ms-playwright"],
    },
    TargetDefinition {
        id: "ccache-cache",
        name: "ccache 缓存",
        category: "developer",
        risk: "review",
        description: "C/C++ 编译缓存。删除后编译速度可能暂时变慢。",
        relative_paths: &[".cache/ccache"],
    },
    TargetDefinition {
        id: "uv-cache",
        name: "uv 缓存",
        category: "developer",
        risk: "review",
        description: "uv Python 包管理器缓存。删除后安装依赖时会重新下载包。",
        relative_paths: &[".cache/uv"],
    },
];

pub const MACOS_CLEANUP_TARGETS: &[TargetDefinition] = &[
    TargetDefinition {
        id: "system-cache",
        name: "系统用户缓存",
        category: "cache",
        risk: "review",
        description: "macOS 用户缓存目录。删除后应用会在需要时重新生成缓存。",
        relative_paths: &["Library/Caches"],
    },
    TargetDefinition {
        id: "user-logs",
        name: "用户日志",
        category: "cache",
        risk: "review",
        description: "macOS 用户日志目录。删除后可能影响应用故障排查。",
        relative_paths: &["Library/Logs"],
    },
    TargetDefinition {
        id: "safari-cache",
        name: "Safari 缓存",
        category: "browser",
        risk: "review",
        description: "Safari 页面资源缓存，不包含书签和密码。",
        relative_paths: &["Library/Caches/com.apple.Safari"],
    },
    TargetDefinition {
        id: "firefox-cache",
        name: "Firefox 缓存",
        category: "browser",
        risk: "review",
        description: "Firefox 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["Library/Caches/Firefox/Profiles"],
    },
    TargetDefinition {
        id: "chrome-cache",
        name: "Chrome 缓存",
        category: "browser",
        risk: "review",
        description: "Chrome 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["Library/Caches/Google/Chrome"],
    },
    TargetDefinition {
        id: "chromium-cache",
        name: "Chromium 缓存",
        category: "browser",
        risk: "review",
        description: "Chromium 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["Library/Caches/Chromium"],
    },
    TargetDefinition {
        id: "brave-cache",
        name: "Brave 缓存",
        category: "browser",
        risk: "review",
        description: "Brave 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["Library/Caches/BraveSoftware"],
    },
    TargetDefinition {
        id: "edge-cache",
        name: "Edge 缓存",
        category: "browser",
        risk: "review",
        description: "Microsoft Edge 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["Library/Caches/Microsoft Edge"],
    },
    TargetDefinition {
        id: "vscode-cache",
        name: "VS Code 缓存",
        category: "developer",
        risk: "review",
        description: "编辑器缓存、Webview 缓存和扩展缓存。删除后可能需要重新加载部分资源。",
        relative_paths: &[
            "Library/Application Support/Code/Cache",
            "Library/Application Support/Code/CachedData",
            "Library/Application Support/Code/GPUCache",
            "Library/Application Support/Code/logs",
        ],
    },
    TargetDefinition {
        id: "cargo-cache",
        name: "Cargo 缓存",
        category: "developer",
        risk: "review",
        description: "Cargo 包和 Git 依赖缓存。删除后构建 Rust 项目时会重新下载依赖。",
        relative_paths: &[".cargo/registry/cache", ".cargo/git/db"],
    },
    TargetDefinition {
        id: "go-cache",
        name: "Go 构建缓存",
        category: "developer",
        risk: "review",
        description: "Go 构建和模块下载缓存。删除后构建时会重新生成或下载依赖。",
        relative_paths: &["Library/Caches/go-build", "go/pkg/mod/cache"],
    },
    TargetDefinition {
        id: "playwright-cache",
        name: "Playwright 缓存",
        category: "developer",
        risk: "review",
        description: "Playwright 下载的浏览器缓存。删除后运行测试时会重新下载浏览器。",
        relative_paths: &["Library/Caches/ms-playwright"],
    },
    TargetDefinition {
        id: "uv-cache",
        name: "uv 缓存",
        category: "developer",
        risk: "review",
        description: "uv Python 包管理器缓存。删除后安装依赖时会重新下载包。",
        relative_paths: &["Library/Caches/uv"],
    },
];

pub const WINDOWS_CLEANUP_TARGETS: &[TargetDefinition] = &[
    TargetDefinition {
        id: "temp-files",
        name: "临时文件",
        category: "cache",
        risk: "review",
        description: "Windows 用户临时目录。正在使用的文件会清理失败并保留。",
        relative_paths: &["AppData/Local/Temp"],
    },
    TargetDefinition {
        id: "thumbnail-cache",
        name: "缩略图缓存",
        category: "cache",
        risk: "safe",
        description: "资源管理器缩略图缓存。删除后系统会在需要时重新生成。",
        relative_paths: &["AppData/Local/Microsoft/Windows/Explorer"],
    },
    TargetDefinition {
        id: "inet-cache",
        name: "系统网络缓存",
        category: "cache",
        risk: "review",
        description: "Windows 用户网络缓存。删除后系统会按需重建。",
        relative_paths: &["AppData/Local/Microsoft/Windows/INetCache"],
    },
    TargetDefinition {
        id: "firefox-cache",
        name: "Firefox 缓存",
        category: "browser",
        risk: "review",
        description: "Firefox 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["AppData/Local/Mozilla/Firefox/Profiles"],
    },
    TargetDefinition {
        id: "chrome-cache",
        name: "Chrome 缓存",
        category: "browser",
        risk: "review",
        description: "Chrome 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["AppData/Local/Google/Chrome/User Data/Default/Cache"],
    },
    TargetDefinition {
        id: "edge-cache",
        name: "Edge 缓存",
        category: "browser",
        risk: "review",
        description: "Microsoft Edge 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["AppData/Local/Microsoft/Edge/User Data/Default/Cache"],
    },
    TargetDefinition {
        id: "brave-cache",
        name: "Brave 缓存",
        category: "browser",
        risk: "review",
        description: "Brave 页面资源缓存，不包含书签、密码和历史记录。",
        relative_paths: &["AppData/Local/BraveSoftware/Brave-Browser/User Data/Default/Cache"],
    },
    TargetDefinition {
        id: "vscode-cache",
        name: "VS Code 缓存",
        category: "developer",
        risk: "review",
        description: "编辑器缓存、Webview 缓存和扩展缓存。删除后可能需要重新加载部分资源。",
        relative_paths: &[
            "AppData/Roaming/Code/Cache",
            "AppData/Roaming/Code/CachedData",
            "AppData/Roaming/Code/GPUCache",
            "AppData/Roaming/Code/logs",
        ],
    },
    TargetDefinition {
        id: "cargo-cache",
        name: "Cargo 缓存",
        category: "developer",
        risk: "review",
        description: "Cargo 包和 Git 依赖缓存。删除后构建 Rust 项目时会重新下载依赖。",
        relative_paths: &[".cargo/registry/cache", ".cargo/git/db"],
    },
    TargetDefinition {
        id: "go-cache",
        name: "Go 构建缓存",
        category: "developer",
        risk: "review",
        description: "Go 构建和模块下载缓存。删除后构建时会重新生成或下载依赖。",
        relative_paths: &["AppData/Local/go-build", "go/pkg/mod/cache"],
    },
    TargetDefinition {
        id: "playwright-cache",
        name: "Playwright 缓存",
        category: "developer",
        risk: "review",
        description: "Playwright 下载的浏览器缓存。删除后运行测试时会重新下载浏览器。",
        relative_paths: &["AppData/Local/ms-playwright"],
    },
    TargetDefinition {
        id: "uv-cache",
        name: "uv 缓存",
        category: "developer",
        risk: "review",
        description: "uv Python 包管理器缓存。删除后安装依赖时会重新下载包。",
        relative_paths: &["AppData/Local/uv/cache"],
    },
];
